version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
            - v2-npm-
      - run: 
          name: Install packages
          command: npm install
      - save_cache:
          name: Save NPM cache
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - restore_cache:
          name: Save Gem cache
          keys:
            - v2-bundle-{{ checksum "Gemfile.lock" }}
            - v2-bundle-
      - run: 
          name: Install vendor bundle
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Save vendor bundle cache
          key: v2-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: 
          name: Build
          command: npm run build
      - run: 
          name: Test HTML URLs
          command: bundle exec htmlproofer --http-status-ignore "999" --url-swap "https\://digitalcorps.gsa.gov:" _site

workflows:
  version: 2
  test:
    jobs:
      - build
